### ISSUE TITLE
Untyped Lazy or Provider exception

### ISSUE THREAD

**Issue by dlemures** [stephanenicolas/toothpick#138]
When Lazies don't include the type parameter, we just get an internal exception (OutOfIndex...):
```java
@Inject Lazy lazy;
@Inject Provider provider;

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at com.sun.tools.javac.util.List.get(List.java:476)
	at toothpick.compiler.common.ToothpickProcessor.getKindParameter(ToothpickProcessor.java:422)
	at toothpick.compiler.common.ToothpickProcessor.getInjectedType(ToothpickProcessor.java:277)
...
```

We should throw a proper error instead.

**Comment by dlemures** [comment]
Solved in 1.0.0-RC7
https://github.com/stephanenicolas/toothpick/pull/137
