### ISSUE TITLE
Jacoco fails because of $ in .class name -- Gradle 2.14.1

### ISSUE THREAD

**Issue by philipbjorge** [stephanenicolas/toothpick#144]
When trying to run jacoco to gather test coverage reports, it failed generating the test report.

```
Caused by: java.io.FileNotFoundException: /Users/philipbjorge/Leafly/leafly-android-next/app/build/intermediates/classes/release/com/leafly/leaflynext/activities/MainActivity$Factory.class (No such file or directory)
        at org.apache.tools.ant.types.resources.FileResource.getInputStream(FileResource.java:217)
        at org.jacoco.ant.ReportTask.createBundle(ReportTask.java:569)
        at org.jacoco.ant.ReportTask.createReport(ReportTask.java:542)
        at org.jacoco.ant.ReportTask.execute(ReportTask.java:495)
```

Turns out this is a gradle bug that has since been fixed in Gradle 3.0

https://discuss.gradle.org/t/java-io-filenotfoundexception-when-running-jacoco-inside-an-android-kotlin-project/18675

Not sure if this is something you'd like to fix or not, but I thought it'd be worth getting in your issues tracker in case others run into it.

**Comment by stephanenicolas** [comment]
Thx @philipbjorge. The workaround we used for gradle < 3 was : 

```java
  new File("${buildDir}/intermediates/classes/debug").eachFileRecurse { file ->
    if (file.name.contains('$$')) {
      file.renameTo(file.path.replace('$$', '$'))
    }
  }
```

in our custom `jacocoTestReport` task. 

I close the issue as there is not much we can do here, we provide a workaround and gradle 3 fixes it..

Thx for reporting, it will probably help others !

**Comment by stephanenicolas** [comment]
(marked as invalid bug as there is a bug, but in gradle ;)
