### ISSUE TITLE
Handling Retrofit multiple dependent providers

### ISSUE THREAD

**Issue by afaucogney** [stephanenicolas/toothpick#244]
I'not used to work with DI, but from theory point of view I decided to go to Toothpick for clarity and simplicity. However I got some issue resolving injection of Retrofit in my app.

I create a module "NetworkModule"

```
public class NetworkModule extends Module {
    public NetworkModule(String urlPath) {
        bind(Gson.class).toProvider(GsonProvider.class);
        bind(Retrofit.class).toProviderInstance(new RetrofitProvider(urlPath, new GsonProvider().get()));
}
```

As you see some providers depends from others. RetrofitProvider need previously injected Gson dependency. How to deal with that ?

**Comment by kelsos** [comment]
You could do this the following way.

Add a named binding for the path:
```java
bind(String.class).withName("urlPath").toInstance(urlPath);
```
Bind to the provider class instead and make it so that it is singleton in the scope.
```java
bind(Retrofit.class).toProvider(RetrofitProvider.class).singletonInScope();
```
And you could use the **\@Inject** annotation to the constructor of the provider to inject the path and Gson instance.
```java
public class RetrofitProvider<Retrofit> implements Provider<Retrofit> {

  private final Gson gson;
  private final String urlPath;

  @Inject
  public RetrofitProvider(Gson gson, @Named("urlPath") String urlPath) {
    this.gson = gson;
    this.urlPath = urlPath;
  }

  @Override
  public Retrofit get() {
    ...
  }
}
```

This is how I would do it.

**Comment by afaucogney** [comment]
@kelsos thanks for helping. It is more Gson instance that needed to be injected. So I did implement your proposal like this:

public class NetworkModule extends Module {

```
    public NetworkModule(String urlPath) {
        bind(String.class).withName("urlPath").toInstance(urlPath);
        bind(Gson.class).withName("gson").toProvider(GsonProvider.class).singletonInScope();
        bind(OkHttpClient.class).withName("client").toProvider(OkHttpClientProvider.class).singletonInScope();
        bind(Retrofit.class).toProvider(RetrofitProvider.class).singletonInScope();
    }
```

and providers in kotlin

```
class GsonProvider : Provider<Gson> {
    override fun get(): Gson {
        return GsonBuilder().create()
    }
}

class OkHttpClientProvider : Provider<OkHttpClient> {
    override fun get(): OkHttpClient {
        return OkHttpClient.Builder()
                .readTimeout(40, TimeUnit.SECONDS)
                .writeTimeout(40, TimeUnit.SECONDS)
                .build()
    }
}

class RetrofitProvider @Inject constructor(
        @Named("urlPath") private var urlPath: String,
        @Named("gson") private var gson: Gson,
        @Named("client") private var client: OkHttpClient)
    : Provider<Retrofit> {

    override fun get(): Retrofit {
        return Retrofit
                .Builder()
                .addCallAdapterFactory(RxJava2CallAdapterFactory.createWithScheduler(Schedulers.io()))
                .baseUrl(urlPath)
                .client(client)
                .addConverterFactory(GsonConverterFactory.create(gson))
                .build()
    }
}
```

and I get this:

```
RuntimeException: Unable to start activity ComponentInfo{...} toothpick.registries.NoFactoryFoundException: No factory could be found for class retrofit2.Retrofit. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members. If using Registries, check that they are properly setup with annotation processor arguments.

Caused by: toothpick.registries.NoFactoryFoundException: No factory could be found for class retrofit2.Retrofit. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members. If using Registries, check that they are properly setup with annotation processor arguments.
```

**Comment by kelsos** [comment]
I would guess from the error that the Module was not properly installed on it's scope when the inject method was called. At least, most of the times I have seen this error with external dependencies and providers that was the case.

**Comment by dlemures** [comment]
hi @afaucogney ,

#### Providing URL 

The @kelsos idea of using a named binding for the url is great:
```java
bind(String.class).withName("urlPath").toInstance(urlPath);
```
However, why do you use named bindings for `Gson` and `OkHttpClient`?

#### Reusing instances

If you want `Gson`, `OkHttpClient` and `Retrofit` to be singletons, i'd recommend to annotate the providers with `@Singleton` and `@ProvidesSingletonInScope`.

You can do the same by adding to the binding `.providesSingletonInScope()`. 

However, `.singletonInScope()` is not equivalent. It means that the provider will be a singleton, but not the instance that it provides.

#### Factory not found issue

Could you provide the whole stacktrace, the piece of code where you install the module and the one where you inject?

**Comment by afaucogney** [comment]
I wrote another project with KotlinWeather to illustrate my issue, but it goes away. So I will check deeper what are the diff to better understand.

Nevertheless, https://github.com/afaucogney/KotlinWeather/tree/MoreInjection can be review. I transform the project to inject all okhhtpclient, url, retrofit and api with TP.

At the end does it make sense, better sens or no sens ? Please advise me with some educated hints. 

FYI @ekamp

**Comment by kelsos** [comment]
@dlemures You are right, my mistake. I remember reading about the difference either on the wiki or on an issue, I don't clearly remember where, but it seems that I completely forgot about the providesSingletonInScope. Now I am inclined to check my projects, because I am almost certain that there is some code that uses the wrong method call :D

**Comment by ekamp** [comment]
@afaucogney this is pretty cool! Mind opening a PR for this change ?

**Comment by afaucogney** [comment]
@ekamp as soon as I fully understand what I did, I will do ;)

**Comment by afaucogney** [comment]
@kelsos @dlemures 
I remade another project and I still get the same issue with a simple injection. Could you please check it:

https://github.com/afaucogney/TestToothpick
```

E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.niji.systemu.testtoothpick, PID: 30338
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.niji.systemu.testtoothpick/com.niji.systemu.testtoothpick.MainActivity}: toothpick.registries.NoFactoryFoundException: No factory could be found for class com.niji.systemu.testtoothpick.GsonProvider. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members. If using Registries, check that they are properly setup with annotation processor arguments.
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2666)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                                                    Caused by: toothpick.registries.NoFactoryFoundException: No factory could be found for class com.niji.systemu.testtoothpick.GsonProvider. Check that the class has either a @Inject annotated constructor or contains @Inject annotated members. If using Registries, check that they are properly setup with annotation processor arguments.
                                                       at toothpick.registries.FactoryRegistryLocator.getFactoryUsingReflection(FactoryRegistryLocator.java:57)
                                                       at toothpick.configuration.ReflectionOnConfiguration.getFactory(ReflectionOnConfiguration.java:11)
                                                       at toothpick.configuration.Configuration.getFactory(Configuration.java:113)
                                                       at toothpick.registries.FactoryRegistryLocator.getFactory(FactoryRegistryLocator.java:38)
                                                       at toothpick.InternalProviderImpl.get(InternalProviderImpl.java:103)
                                                       at toothpick.ScopeImpl.getInstance(ScopeImpl.java:58)
                                                       at toothpick.ScopeImpl.getInstance(ScopeImpl.java:49)
                                                       at com.niji.systemu.testtoothpick.MainActivity$$MemberInjector.inject(MainActivity$$MemberInjector.java:11)
                                                       at com.niji.systemu.testtoothpick.MainActivity$$MemberInjector.inject(MainActivity$$MemberInjector.java:8)
                                                       at toothpick.InjectorImpl.inject(InjectorImpl.java:25)
                                                       at toothpick.Toothpick.inject(Toothpick.java:140)
                                                       at com.niji.systemu.testtoothpick.MainActivity.onCreate(MainActivity.kt:24)
                                                       at android.app.Activity.performCreate(Activity.java:6682)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                    Caused by: java.lang.ClassNotFoundException: com.niji.systemu.testtoothpick.GsonProvider$$Factory
                                                       at java.lang.Class.classForName(Native Method)
                                                       at java.lang.Class.forName(Class.java:400)
                                                       at java.lang.Class.forName(Class.java:326)
                                                       at toothpick.registries.FactoryRegistryLocator.getFactoryUsingReflection(FactoryRegistryLocator.java:54)
                                                       at toothpick.configuration.ReflectionOnConfiguration.getFactory(ReflectionOnConfiguration.java:11) 
                                                       at toothpick.configuration.Configuration.getFactory(Configuration.java:113) 
                                                       at toothpick.registries.FactoryRegistryLocator.getFactory(FactoryRegistryLocator.java:38) 
                                                       at toothpick.InternalProviderImpl.get(InternalProviderImpl.java:103) 
                                                       at toothpick.ScopeImpl.getInstance(ScopeImpl.java:58) 
                                                       at toothpick.ScopeImpl.getInstance(ScopeImpl.java:49) 
                                                       at com.niji.systemu.testtoothpick.MainActivity$$MemberInjector.inject(MainActivity$$MemberInjector.java:11) 
                                                       at com.niji.systemu.testtoothpick.MainActivity$$MemberInjector.inject(MainActivity$$MemberInjector.java:8) 
                                                       at toothpick.InjectorImpl.inject(InjectorImpl.java:25) 
                                                       at toothpick.Toothpick.inject(Toothpick.java:140) 
                                                       at com.niji.systemu.testtoothpick.MainActivity.onCreate(MainActivity.kt:24) 
                                                       at android.app.Activity.performCreate(Activity.java:6682) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 
                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.niji.systemu.testtoothpick.GsonProvider$$Factory" on path: DexPathList[[zip file "/data/app/com.niji.systemu.testtoothpick-2/base.apk"],nativeLibraryDirectories=[/data/app/com.niji.systemu.testtoothpick-2/lib/arm64, /system/lib64, /vendor/lib64]]
                                                       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                       at java.lang.Class.classForName(Native Method) 
                                                       at java.lang.Class.forName(Class.java:400) 
                                                       at java.lang.Class.forName(Class.java:326) 
                                                       at toothpick.registries.FactoryRegistryLocator.getFactoryUsingReflection(FactoryRegistryLocator.java:54) 
                                                       at toothpick.configuration.ReflectionOnConfiguration.getFactory(ReflectionOnConfiguration.java:11) 
                                                       at toothpick.configuration.Configuration.getFactory(Configuration.java:113) 
                                                       at toothpick.registries.FactoryRegistryLocator.getFactory(FactoryRegistryLocator.java:38) 
                                                       at toothpick.InternalProviderImpl.get(InternalProviderImpl.java:103) 
                                                       at toothpick.ScopeImpl.getInstance(ScopeImpl.java:58) 
                                                       at toothpick.ScopeImpl.getInstance(ScopeImpl.java:49) 
                                                       at com.niji.systemu.testtoothpick.MainActivity$$MemberInjector.inject(MainActivity$$MemberInjector.java:11) 
                                                       at com.niji.systemu.testtoothpick.MainActivity$$MemberInjector.inject(MainActivity$$MemberInjector.java:8) 
                                                       at toothpick.InjectorImpl.inject(InjectorImpl.java:25) 
                                                       at toothpick.Toothpick.inject(Toothpick.java:140) 
                                                       at com.niji.systemu.testtoothpick.MainActivity.onCreate(MainActivity.kt:24) 
                                                       at android.app.Activity.performCreate(Activity.java:6682) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727) 
                                                       at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:154) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:6121) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) 

```
I do not know what I missed

**Comment by kelsos** [comment]
Try adding a inject annotation to the constructor of the provider.

**Comment by afaucogney** [comment]
@kelsos ok thank for the fix.
